### ISSUE TITLE
Make me collaborator

### ISSUE THREAD

**Issue by grunwald** [adamhsparks/Reproducible-Research-in-Plant-Pathology#7]
Hi Adam, please add me as a collaborator to this repository. Thanks!

**Comment by adamhsparks** [comment]
Hi Nick,
You've been invited, you've just not accepted the invite yet. :)

Let me know if this works: https://github.com/adamhsparks/Reproducible-Research-in-Plant-Pathology/invitations

**Comment by adamhsparks** [comment]
@grunwald did this work or do I need to try again?
